LOCAL_PATH := $(call my-dir)

#--------------------------------------------------------------------
include $(CLEAR_VARS)
LOCAL_TARGET := libParamOpt.a
LOCAL_SRCS   := $(wildcard $(LOCAL_PATH)/*.cpp)
NONE_SRCS			:= $(LOCAL_PATH)/test_param.cpp
LOCAL_CFLAGS := -Werror
LOCAL_LDFLAGS:= -lstdc++ -lpthread
LOCAL_LIBS	 := libNormal.a

include $(BUILD_APP)

.PHONY: $(LOCAL_TARGET)

$(LOCAL_TARGET):$(LOCAL_MODULE)
	@echo "Build $@ Done."

$(call add-target-into-build, $(LOCAL_TARGET))
