LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

#------------------------------------------------
LOCAL_TARGET	:= libHttpParser.a
LOCAL_SRCS		:= $(LOCAL_PATH)/match.c $(LOCAL_PATH)/parseformdata.c
LOCAL_CFLAGS	:= -Werror
LOCAL_LDFLAGS	:= -lstdc++ -pthread
LOCAL_LIBS		:= 

include $(BUILD_APP)

.PHONY:	$(LOCAL_TARGET)

$(LOCAL_TARGET): $(LOCAL_MODULE)
	@echo "Build $@ Done"
	
$(call add-target-into-build, $(LOCAL_TARGET))