LOCAL_PATH := $(call my-dir)
include $(CLEAR_VARS)

#------------------------------------------------
LOCAL_TARGET	:= libMd5.a
LOCAL_SRCS		:= $(LOCAL_PATH)/md5.c
LOCAL_CFLAGS	:= -Werror
LOCAL_LDFLAGS	:= 
LOCAL_LIBS		:=

include $(BUILD_APP)

.PHONY:	$(LOCAL_TARGET)

$(LOCAL_TARGET): $(LOCAL_MODULE)
	@echo "Build $@ Done"
	
$(call add-target-into-build, $(LOCAL_TARGET))